// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var LabJson = require("./lab.json");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function decodeProps(json) {
  var hover = function (json) {
    return /* record */[
            /* opacity */Json_decode.field("opacity", Json_decode.$$int, json),
            /* transition */Json_decode.field("transition", Json_decode.string, json)
          ];
  };
  var active = function (json) {
    return /* record */[
            /* opacity */Json_decode.field("opacity", Json_decode.$$int, json),
            /* transition */Json_decode.field("transition", Json_decode.string, json)
          ];
  };
  return /* record */[
          /* src */Json_decode.optional((function (param) {
                  return Json_decode.field("src", Json_decode.string, param);
                }), json),
          /* w */Json_decode.optional((function (param) {
                  return Json_decode.field("w", Json_decode.$$int, param);
                }), json),
          /* mt */Json_decode.optional((function (param) {
                  return Json_decode.field("mt", Json_decode.$$int, param);
                }), json),
          /* mb */Json_decode.optional((function (param) {
                  return Json_decode.field("mb", Json_decode.$$int, param);
                }), json),
          /* my */Json_decode.optional((function (param) {
                  return Json_decode.field("my", Json_decode.$$int, param);
                }), json),
          /* fontSize */Json_decode.optional((function (param) {
                  return Json_decode.field("fontSize", (function (param) {
                                return Json_decode.array(Json_decode.$$int, param);
                              }), param);
                }), json),
          /* fontWeight */Json_decode.optional((function (param) {
                  return Json_decode.field("fontWeight", Json_decode.string, param);
                }), json),
          /* color */Json_decode.optional((function (param) {
                  return Json_decode.field("colors", Json_decode.string, param);
                }), json),
          /* borderColor */Json_decode.optional((function (param) {
                  return Json_decode.field("borderColor", Json_decode.string, param);
                }), json),
          /* hover */Json_decode.optional((function (param) {
                  return Json_decode.field("hover", hover, param);
                }), json),
          /* active */Json_decode.optional((function (param) {
                  return Json_decode.field("active", active, param);
                }), json)
        ];
}

function decodeStyle(json) {
  return /* record */[
          /* display */Json_decode.optional((function (param) {
                  return Json_decode.field("display", Json_decode.string, param);
                }), json),
          /* maxWidth */Json_decode.optional((function (param) {
                  return Json_decode.field("maxWidth", Json_decode.string, param);
                }), json),
          /* textTransform */Json_decode.optional((function (param) {
                  return Json_decode.field("textTransform", Json_decode.string, param);
                }), json),
          /* letterSpacing */Json_decode.optional((function (param) {
                  return Json_decode.field("letterSpacing", Json_decode.string, param);
                }), json),
          /* lineHeight */Json_decode.optional((function (param) {
                  return Json_decode.field("lineHeight", Json_decode.string, param);
                }), json),
          /* textDecoration */Json_decode.optional((function (param) {
                  return Json_decode.field("textDecoration", Json_decode.string, param);
                }), json),
          /* whiteSpace */Json_decode.optional((function (param) {
                  return Json_decode.field("whiteSpace", Json_decode.string, param);
                }), json),
          /* transition */Json_decode.optional((function (param) {
                  return Json_decode.field("transition", Json_decode.string, param);
                }), json),
          /* opacity */Json_decode.optional((function (param) {
                  return Json_decode.field("opacity", Json_decode.$$int, param);
                }), json),
          /* height */Json_decode.optional((function (param) {
                  return Json_decode.field("height", Json_decode.string, param);
                }), json),
          /* width */Json_decode.optional((function (param) {
                  return Json_decode.field("width", Json_decode.string, param);
                }), json),
          /* overflow */Json_decode.optional((function (param) {
                  return Json_decode.field("overflow", Json_decode.string, param);
                }), json),
          /* textAlign */Json_decode.optional((function (param) {
                  return Json_decode.field("textAlign", Json_decode.string, param);
                }), json)
        ];
}

function decodeComponent(json) {
  return /* record */[
          /* name */Json_decode.field("name", Json_decode.string, json),
          /* type_ */Json_decode.optional((function (param) {
                  return Json_decode.field("type", Json_decode.string, param);
                }), json),
          /* props */Json_decode.optional((function (param) {
                  return Json_decode.field("props", decodeProps, param);
                }), json),
          /* style */Json_decode.optional((function (param) {
                  return Json_decode.field("style", decodeStyle, param);
                }), json),
          /* examples */Json_decode.field("examples", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), json),
          /* system */Json_decode.optional((function (param) {
                  return Json_decode.field("system", (function (param) {
                                return Json_decode.array(Json_decode.string, param);
                              }), param);
                }), json),
          /* imports */Json_decode.optional((function (param) {
                  return Json_decode.field("imports", (function (param) {
                                return Json_decode.array(Json_decode.string, param);
                              }), param);
                }), json),
          /* jsx */Json_decode.optional((function (param) {
                  return Json_decode.field("jsx", Json_decode.string, param);
                }), json),
          /* keyword */Json_decode.optional((function (param) {
                  return Json_decode.field("keyword", (function (param) {
                                return Json_decode.array(Json_decode.string, param);
                              }), param);
                }), json),
          /* description */Json_decode.optional((function (param) {
                  return Json_decode.field("description", Json_decode.string, param);
                }), json)
        ];
}

function decodeComponents(json) {
  return Json_decode.list(decodeComponent, json);
}

var json = LabJson.components;

console.log(Json_decode.list(decodeComponent, json));

exports.decodeProps = decodeProps;
exports.decodeStyle = decodeStyle;
exports.decodeComponent = decodeComponent;
exports.decodeComponents = decodeComponents;
/*  Not a pure module */
