// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");
var LabJson = require("./lab.json");

var x = LabJson.components;

var x2 = Belt_List.fromArray(x);

console.log("length using list length: ", Belt_List.length(x2));

console.log(x2);

exports.x = x;
exports.x2 = x2;
/* x Not a pure module */
