// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var LabJson = require("./lab.json");

var components = LabJson.components;

console.log("Hello, BuckleScript and Reason!");

exports.components = components;
/* components Not a pure module */
